### ISSUE TITLE
Could not build on iOS [v1.0.36]

### ISSUE THREAD

**Issue by shashikantshaale** [muslimtv/flutter_playout#59]
[   +3 ms] Failed to build iOS app
[   +1 ms] Error output from Xcode build:
           ↳
[        ]     ** BUILD FAILED **
[        ] Xcode's output:
           ↳
[        ]     /Users/shashikantdurge/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_playout-1.0.36/ios/Classes/VideoPlayer.swift:13:8: error: no such module 'av_malibrary'
               import av_malibrary
                      ^

Flutter doctor output:
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-IN)
    • Flutter version 1.17.5 at /Users/shashikantdurge/development/flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/shashikantdurge/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone • 98ca07e3d86d8b3fea6272de95e3604e225a77a4 • ios • iOS 13.5.1

• No issues found!
```

**Comment by shashikantshaale** [comment]
This is working fine in 1.0.35

**Comment by KhuramKhalid** [comment]
Yes the last update broke the iOS implementation. Please keep using 1.0.35 until I push out the fix.

**Comment by KhuramKhalid** [comment]
Fixed in 1.0.37
